const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointCount,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.OnFrameChanged
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{intro_: 0},
	{Sine: 0},
	{txt_taptocontinue: 0},
	{Touch: 0},
	{debug: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{fade: 0},
	{Anchor: 0},
	{txt_reset: 0},
	{btn_main: 0},
	{btn_sound: 0},
	{btn_music: 0},
	{bgPaused: 0},
	{b_play: 0},
	{txt_ver: 0},
	{txt_score: 0},
	{fontSizeDefault: 0},
	{rew: 0},
	{txt_gameover: 0},
	{Tween: 0},
	{btn_restartGame: 0},
	{btn_fullscreen: 0},
	{btn_info: 0},
	{txt_infoBack: 0},
	{Browser: 0},
	{Pin: 0},
	{txt_credits: 0},
	{txt_howTo: 0},
	{btn_gotit: 0},
	{memX: 0},
	{iniX: 0},
	{moveMinX: 0},
	{moveMaxX: 0},
	{delete: 0},
	{color: 0},
	{powerUp: 0},
	{block: 0},
	{Keyboard: 0},
	{memColor: 0},
	{slot: 0},
	{p_id: 0},
	{baseSlot: 0},
	{wall: 0},
	{checkR: 0},
	{checkL: 0},
	{blockEffect: 0},
	{Bg: 0},
	{cursor: 0},
	{matchEffect: 0},
	{bgHud: 0},
	{title: 0},
	{checkEndLine: 0},
	{defaultSize: 0},
	{txt_powerUp: 0},
	{type: 0},
	{rewCount: 0},
	{btn_powerUp: 0},
	{memText: 0},
	{Flash: 0},
	{txt_powerUpLabel: 0},
	{btn_powerUpIcon: 0},
	{btn_boardUI: 0},
	{howToPic: 0},
	{bgGame: 0},
	{boardGame: 0},
	{Sine2: 0},
	{topGem: 0},
	{rew_icon: 0},
	{btn_continueReward: 0},
	{GameDistributionSDK: 0},
	{TopButtons: 0},
	{load_ok: 0},
	{storageName: 0},
	{score: 0},
	{hScore: 0},
	{selectedBlock: 0},
	{creating: 0},
	{new: 0},
	{pieceColors: 0},
	{matching: 0},
	{starting: 0},
	{colorBlock: 0},
	{powerUpColor: 0},
	{powerUpLine: 0},
	{powerUpExtraMove: 0},
	{gameOver: 0},
	{rew_type: 0},
	{pos: 0},
	{count: 0},
	{p_color: 0},
	{p_Y: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{control: 0}
];

self.InstanceType = {
	intro_: class extends self.ISpriteInstance {},
	txt_taptocontinue: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	debug: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	txt_reset: class extends self.ITextInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	b_play: class extends self.ISpriteInstance {},
	txt_ver: class extends self.ITextInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_gameover: class extends self.ITextInstance {},
	btn_restartGame: class extends self.ISpriteInstance {},
	btn_fullscreen: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	txt_infoBack: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	txt_credits: class extends self.ITextInstance {},
	txt_howTo: class extends self.ITextInstance {},
	btn_gotit: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	slot: class extends self.ISpriteInstance {},
	baseSlot: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	checkR: class extends self.ISpriteInstance {},
	checkL: class extends self.ISpriteInstance {},
	blockEffect: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	cursor: class extends self.ITiledBackgroundInstance {},
	matchEffect: class extends self.ISpriteInstance {},
	bgHud: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	checkEndLine: class extends self.ISpriteInstance {},
	txt_powerUp: class extends self.ITextInstance {},
	btn_powerUp: class extends self.ISpriteInstance {},
	txt_powerUpLabel: class extends self.ITextInstance {},
	btn_powerUpIcon: class extends self.ISpriteInstance {},
	btn_boardUI: class extends self.ISpriteInstance {},
	howToPic: class extends self.ISpriteInstance {},
	bgGame: class extends self.ITiledBackgroundInstance {},
	boardGame: class extends self.ISpriteInstance {},
	topGem: class extends self.ISpriteInstance {},
	rew_icon: class extends self.ISpriteInstance {},
	btn_continueReward: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	TopButtons: class extends self.ISpriteInstance {}
}